language: node_js

matrix:
  include:
    - os: linux
      node_js: "8"
    - os: linux
      node_js: "7"
    - os: linux
      node_js: "6"

    - os: osx
      node_js: "8"
    - os: osx
      node_js: "7"
    - os: osx
      node_js: "6"

script:
  - yarn test
  - python lib/one/solution.py